### ISSUE TITLE
Run/Deploy

### ISSUE THREAD

**Issue by Anonymous0064** [gokulkrishh/habits-tracker#7]
Hey Gokul!! I just wanna know how can i run/Deploy for myself? Can i use your code?? Please guide me to deploy as a site. (I am Newbie)

**Comment by gokulkrishh** [comment]
@Anonymous0064 Yes, you can use my code. It's a simple web application. 

Build command: https://github.com/gokulkrishh/habits-tracker/blob/master/package.json#L20
